"""설정 모듈"""
from .constants import (
    RECORDER_VERSION,
    HOTKEY,
    PLAY_HOTKEY,
    RECORD_START_HOTKEY,
    RECORD_STOP_HOTKEY,
    SUPPRESS_HOTKEY,
    DID_DISABLE_UNDO_REDO_ONCE,
    SPECIAL_KEYS,
)

__all__ = [
    'RECORDER_VERSION',
    'HOTKEY',
    'PLAY_HOTKEY',
    'RECORD_START_HOTKEY',
    'RECORD_STOP_HOTKEY',
    'SUPPRESS_HOTKEY',
    'DID_DISABLE_UNDO_REDO_ONCE',
    'SPECIAL_KEYS',
]
